// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl8RVz1KvNHD7PSUW4XYbxAV0fhhksrKs',
    appId: '1:251170387434:web:49fb59fbb80e06da89ee93',
    messagingSenderId: '251170387434',
    projectId: 'mynotes-87740',
    authDomain: 'mynotes-87740.firebaseapp.com',
    storageBucket: 'mynotes-87740.appspot.com',
    measurementId: 'G-H008GJ6RKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLz_o4Dqhl-2PDTr6zypMpi0QuszEYTeY',
    appId: '1:251170387434:android:8082baefe778361d89ee93',
    messagingSenderId: '251170387434',
    projectId: 'mynotes-87740',
    storageBucket: 'mynotes-87740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUkSdpGSccZMp_0JqgIYiz3Ju28SBYQg',
    appId: '1:251170387434:ios:6271733b0676d1ca89ee93',
    messagingSenderId: '251170387434',
    projectId: 'mynotes-87740',
    storageBucket: 'mynotes-87740.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUkSdpGSccZMp_0JqgIYiz3Ju28SBYQg',
    appId: '1:251170387434:ios:6271733b0676d1ca89ee93',
    messagingSenderId: '251170387434',
    projectId: 'mynotes-87740',
    storageBucket: 'mynotes-87740.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl8RVz1KvNHD7PSUW4XYbxAV0fhhksrKs',
    appId: '1:251170387434:web:244792710c64bd2e89ee93',
    messagingSenderId: '251170387434',
    projectId: 'mynotes-87740',
    authDomain: 'mynotes-87740.firebaseapp.com',
    storageBucket: 'mynotes-87740.appspot.com',
    measurementId: 'G-1GVHCMET07',
  );
}
